### ISSUE TITLE
Import script: detect years range in case discrete years list

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#101]
For datasets which have a discrete list of years they support. Find min/max and set as range. Fill in temporal gap field with "only years:...".

**Comment by MeWu-IDM** [comment]
tested with attached data
good enough for demo
[test_catlin_date.csv.txt](https://github.com/InstituteforDiseaseModeling/ckan/files/3769949/test_catlin_date.csv.txt)
