### ISSUE TITLE
Setup calendar reminder for Iteration 2 containing tasks and feedback form

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#110]

**Comment by DLukacevic-IDM** [comment]
Re-assigning per agreement. Thanks Meikang.

**Comment by MeWu-IDM** [comment]
form will be in 
https://forms.office.com/Pages/ResponsePage.aspx?id=AE2ufJnghkaYc7onw1HRHt41AqeTK9FKmya3Ug1-xYVUOE0zR0laMEFaTkRXODdLSUlOWldMVkpVQi4u

**Comment by MeWu-IDM** [comment]
worked with dejan to create calendar items on 1/22 and updated the form
