### ISSUE TITLE
Add dropbox url to description so project folder names are searchable

### ISSUE THREAD

**Issue by mfisher-idmod** [InstituteforDiseaseModeling/ckan#113]
### CKAN Version if known (or site URL)
http://data-catalog

### Please describe the expected behaviour

Malaria users expect to be able to search for data by project names, but their project names are their DropBox folder names and these names aren't on the data sets in the folder directories. If you add the DropBox url to the description, this will be searchable.

I think this may address Kevin's findings as well for Measles team data sets:

> Searched first for the term “WUENIC”, and found no results.  Searched for filename “coverage_series”, the name of an old copy of this data (2015) in the Measles Team Repo - found that old file already imported (2nd search result), along with 24 other datasets that matched the search term “coverage_series”.    Most results did not actually have the full search term, but one of coverage or series.  
> I think the search term WUENIC should return the old dataset in there, but that dataset was not tagged with this name so it’s understandable why it did not – was not able to quickly figure out whether/how I could add this as a tag to the dataset.  Probably can’t since I was not the uploader.

**Comment by DLukacevic-IDM** [comment]
It looks like datasets are already searchable by project names (Dropbox folder names) but only if filde prefix is used. For example "urls:WUENIC" will return the desired dataset. 

So, the work here is to make urls (res_url) fields being considered for the full-text search.

**Comment by MeWu-IDM** [comment]
tested resource url is now searchable
