### ISSUE TITLE
Make Add Dataset more visible, or easier to get to quickly

### ISSUE THREAD

**Issue by mfisher-idmod** [InstituteforDiseaseModeling/ckan#118]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### Please describe the expected behaviour

In the trial, we got feedback from Kevin in Measles and Jon in Malaria that it took awhile to figure out how to add a data set. Perhaps make the Add dataset button bigger or make it easier to get to quickly, e.g. from the Datasets dropdown.

**Comment by MeWu-IDM** [comment]
solution acceptable
