### ISSUE TITLE
If specify other on License and resource; enable custom license

### ISSUE THREAD

**Issue by mfisher-idmod** [InstituteforDiseaseModeling/ckan#120]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### Please describe the expected behaviour
Feedback from Kevin in the trial:
Whenever “License” is not one of the standard licenses, the user should have to enter free form information describing the terms of use.  
Both of these behaviors would enforce stronger practices around data provenance and use restrictions.

**Comment by MeWu-IDM** [comment]
verified
