### ISSUE TITLE
Missing implementations based on Spec 

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/ckan#13]
use this issue to list all fields not as described in
https://wiki.idmod.org/display/SP/Phase+1%3A+Data+Catalog+Prototype

1. Resources:
"Type" is missing but "Purpose" is present 
"Type" does not have all values "Data, Code, Doc, Paper, Origin, Other"

2. Dataset:
"Version" should be required but not enforced

**Comment by DLukacevic-IDM** [comment]
1. Updated the spec and schema definition to match resources type field name and values,
2. I cannot find above statement ("required but not enforced") in the spec it in the spec. Anyways, I think spec and code match for dataset "Version".

**Comment by DLukacevic-IDM** [comment]
After clarification about item 2, I made Version not required.

**Comment by MeWu-IDM** [comment]
validated spec metadata now matched implementation
