### ISSUE TITLE
We should fix or disable the language option for phase 1 version

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/ckan#18]
many languages do not seem to have proper translation for phase 1 we should either fix or disable the selection to avoid confusion
![image](https://user-images.githubusercontent.com/40474438/63134531-aebe4380-bf7e-11e9-8b95-a5d0d0caf293.png)
![image](https://user-images.githubusercontent.com/40474438/63134559-d01f2f80-bf7e-11e9-81fc-13c41f1953af.png)

**Comment by DLukacevic-IDM** [comment]
Language selector removed.
