### ISSUE TITLE
"Previous" button should go back to the previous page without saving the data

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/ckan#26]
When user created a dataset, he can go to the add data by clicking this
![image](https://user-images.githubusercontent.com/40474438/63793626-f4e7a100-c8b4-11e9-99fc-c41e9377677c.png)

Then he will be on this page /dataset/{dataset_id}/resource/new
![image](https://user-images.githubusercontent.com/40474438/63793797-47c15880-c8b5-11e9-83d0-305656e8af25.png)

immediately clicking "Previous" should take him to the /dataset/{dataset_id}/edit page
but the actual behavior is that the user is required to enter the name before he can go back
otherwise he gets validation error below
**_"The form contains invalid entries: Name: Missing value"_**

It seems that every time user click "previous" , he is required to enter the "name" and the name is saved without him clicking the "save" button

after a serious of clicking "previous", I got all the "names" saved to my resources, this can be very confusing to users as they just want to "go back" to the previous page to fix something or review
![image](https://user-images.githubusercontent.com/40474438/63794850-a12a8700-c8b7-11e9-8d31-9d0853953a63.png)

suggestion:
give a warning when user click "previous" about losing all data in the current form and do not save them

**Comment by DLukacevic-IDM** [comment]
See commit comment.

**Comment by MeWu-IDM** [comment]
user can now use "previous" to go back to dataset metadata, but cannot go to the previous resources. open #36 #37 as related issues and close this one.
