### ISSUE TITLE
"finish" button behavior issue

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/ckan#27]
this may be a consequence of issue #26 
expected behavior:
after the user click "save and add another", he is back to the new resource page, without entering info for new resources, he should be able to click "finish"
actual behavior:
the validation on required resource name will prevent the user from click "finish" so he is stuck on this page

basically "finish" should behave as:
if user enter all required information, save the resource and finish
if user does not enter anything, do not save and finish
if user enter "some" info but does not pass validation. show the warning but should allow the user to have "discard" option

**Comment by DLukacevic-IDM** [comment]
See commit comment.

**Comment by MeWu-IDM** [comment]
verified above scenario works
