### ISSUE TITLE
test_coding-standards complains about a list files which includes the files we added

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/ckan#3]
![image](https://user-images.githubusercontent.com/40474438/60632016-af788d00-9db7-11e9-90ac-0e13d73c0b6c.png)

**Comment by MeWu-IDM** [comment]
check if this repros

**Comment by DLukacevic-IDM** [comment]
Confirm IDM ext. code has encoding.
For other extension we said they will be installed (the code won't be the part of our repo).

**Comment by DLukacevic-IDM** [comment]
Done.

**Comment by MeWu-IDM** [comment]
confirm no "idm" related files without the specifying encoding below files will be removed from source after phase 2 , tests quarantined 
AssertionError: The following files are missing an encoding specification: [u'ckanext/spatial/helpers.py', u'ckanext/spatial/plugin.py', u'ckanext/spatial/geoalchemy_common.py', u'ckanext/spatial/interfaces.py', u'ckanext/spatial/controllers/view.py', u'ckanext/spatial/controllers/__init__.py', u'ckanext/spatial/controllers/api.py', u'ckanext/spatial/model/package_extent.py', u'ckanext/spatial/model/__init__.py', u'ckanext/spatial/model/harvested_metadata.py', u'ckanext/spatial/harvesters/base.py', u'ckanext/spatial/harvesters/waf.py', u'ckanext/spatial/harvesters/__init__.py', u'ckanext/spatial/harvesters/csw.py', u'ckanext/spatial/harvesters/gemini.py', u'ckanext/spatial/harvesters/doc.py', u'ckanext/spatial/tests/base.py', u'ckanext/spatial/tests/test_api.py', u'ckanext/spatial/tests/__init__.py', u'ckanext/spatial/tests/test_harvest.py', u'ckanext/spatial/tests/test_csw_client.py', u'ckanext/spatial/tests/test_validation.py', u'ckanext/spatial/tests/xml_file_server.py', u'ckanext/spatial/tests/model/__init__.py', u'ckanext/spatial/tests/model/test_package_extent.py', u'ckanext/spatial/tests/model/test_harvested_metadata.py', u'ckanext/spatial/tests/test_plugin/__init__.py', u'ckanext/spatial/tests/test_plugin/plugin.py', u'ckanext/spatial/tests/lib/test_spatial.py', u'ckanext/spatial/tests/functional/__init__.py', u'ckanext/spatial/tests/functional/test_widgets.py', u'ckanext/spatial/tests/functional/test_package.py', u'ckanext/spatial/commands/spatial.py', u'ckanext/spatial/commands/__init__.py', u'ckanext/spatial/commands/validation.py', u'ckanext/spatial/commands/csw.py', u'ckanext/spatial/lib/__init__.py', u'ckanext/spatial/lib/csw_client.py', u'ckanext/spatial/lib/report.py', u'ckanext/spatial/lib/reports.py', u'ckanext/spatial/validation/__init__.py', u'ckanext/spatial/validation/validation.py', u'ckanext/datesearch/plugin.py', u'ckanext/example_theme_docs/v14_more_custom_css/plugin.py', u'ckanext/example_theme_docs/v03_jinja/plugin.py', u'ckanext/example_theme_docs/v09_snippet/plugin.py', u'ckanext/example_theme_docs/v11_HTML_and_CSS/plugin.py', u'ckanext/example_theme_docs/v19_01_error/plugin.py', u'ckanext/example_theme_docs/v21_custom_jquery_plugin/plugin.py', u'ckanext/example_theme_docs/v20_pubsub/plugin.py', u'ckanext/example_theme_docs/v17_popover/plugin.py', u'ckanext/example_theme_docs/v06_super/plugin.py', u'ckanext/example_theme_docs/v07_helper_function/plugin.py', u'ckanext/example_theme_docs/v05_block/plugin.py', u'ckanext/example_theme_docs/v19_02_error_handling/plugin.py', u'ckanext/example_theme_docs/v10_custom_snippet/plugin.py', u'ckanext/example_theme_docs/v04_ckan_extends/plugin.py', u'ckanext/example_theme_docs/v18_snippet_api/plugin.py', u'ckanext/example_theme_docs/v13_custom_css/plugin.py', u'ckanext/scheming/errors.py', u'ckanext/scheming/converters.py', u'ckanext/scheming/logic.py', u'ckanext/scheming/helpers.py', u'ckanext/scheming/loader.py', u'ckanext/scheming/validation.py', u'ckanext/scheming/commands.py', u'ckanext/scheming/tests/mock_pylons_request.py', u'ckanext/scheming/tests/test_dataset_logic.py', u'ckanext/scheming/tests/test_dataset_display.py', u'ckanext/scheming/tests/test_form_snippets.py', u'ckanext/scheming/tests/test_group_display.py', u'ckanext/scheming/tests/test_load.py', u'ckanext/scheming/tests/plugins.py', u'ckanext/scheming/tests/test_validation.py', u'ckanext/scheming/tests/test_form.py', u'ckanext/scheming/tests/test_group_logic.py']
