### ISSUE TITLE
Remove external web resources

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#33]
Some web resources like images are still being pulled form Internet. 

Turn off the network on the local copy of CKAN and track resources which fail to load.

**Comment by DLukacevic-IDM** [comment]
This can be done by overriding Gravatar core helper methods. Alternative image(s) are required to be used instead of Gravatar images.

**Comment by MeWu-IDM** [comment]
gravatar works
