### ISSUE TITLE
on add resource page "enter" key behavior is going to "previous"

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/ckan#37]
repro
create a new dataset from scratch
when on "add resource" page
enter some stuff
move cursor to "name" field and click "enter" on keyboard
it is going to the "previous" and user will lose data
it seems more reasonable to do the "finish" behavior when user press "enter" key

**Comment by DLukacevic-IDM** [comment]
Added javascript keydown event listener to IDM resource form template. 

This is the simplest solution. The downside is that in case someone changes the name of resource name field it will quietly stop working.

 The better and more verbose solution would be to add this javascript code in the resource name control preset (to be more directly tied to the schema definition and name field). I actually did that but ran into some new bugs, so in the interest of time I decided to go with a simpler more reliable solution.

**Comment by MeWu-IDM** [comment]
verified
