### ISSUE TITLE
Develop the master setup script

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#39]
For seamless deployments to "production" and "stage" prototype environments we need a master setup script (point and shoot) that will do the following:

First deploy:
- clone git repo (can be done manually once to get the script on a machine or let Bamboo do it)
- deploy ckan
- create backup mount if it doesn't exists
- (re)create backup cron job (monitoring is done by Bamboo plan)
- create the first sysadmin user and parse its api guid
- run data bootstrap script (populate metadata and datasets) with above guid
- run volumes backup 

Next deploy (refresh):
- pull the new version from git
- deploy ckan (existing deploy script already removed existing containers)
- create backup mount if it doesn't exists
- update backup and monitoring scripts and cron jobs
- run volumes backup

**Comment by DLukacevic-IDM** [comment]
Taking back to split into deploy and ops tasks.

**Comment by MeWu-IDM** [comment]
tested deploy script
