### ISSUE TITLE
Develop datasets import script

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#40]
Script for importing known datasets from the excel spreadsheet and storing those datasets in a more manageable format.

**Comment by DLukacevic-IDM** [comment]
With commit 61bfe8498c71def586def5b0a71225ca12038616 import script is complete.

We still need to create a mapping file for Kevin's spreadsheet and import it. 
I filed #68 to track this work which should happen before we start the trial.

**Comment by MeWu-IDM** [comment]
close this one as scripts for Kaitlin is done
