### ISSUE TITLE
Setup prototype VMs provided by Ops

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#42]
This work includes running the master deploy script and standing up Data Catalog instance on two VMs provided by Ops ("production" and "stage").

Production will be used by researchers during trial. Stage will be used for final verification of new prototype version.

from #64
We need to have docker environment set up consistently with a fixed version

Currently for centos we should follow these instructions:

the instruction is https://docs.docker.com/install/linux/docker-ce/centos/
https://github.com/docker/compose/releases

**Comment by MeWu-IDM** [comment]
tested the docker installation per readme, it works~
