### ISSUE TITLE
Maintainer field issues

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/ckan#54]
2 issues regarding to feature #38
1. Internal server error when updating the dataset with auto-complete maintainer
repro: try to edit an existing dataset type some prefix and let autocomplete find a username

Request URL: http://idmppwks087:5000/dataset/edit/test123
Request Method: POST
Status Code: 500 INTERNAL SERVER ERROR
Remote Address: 10.210.73.126:5000
Referrer Policy: no-referrer-when-downgrade
Content-Length: 5458
Content-Type: text/html; charset=utf-8
Date: Tue, 24 Sep 2019 22:34:31 GMT
Server: PasteWSGIServer/0.5 Python/2.7.13
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Content-Length: 826
Content-Type: application/x-www-form-urlencoded
Cookie: auth_tkt="3d90bd707c2ce2cab16115757d81cbbd5d8a9303testuser!userid_type=unicode"; ckan=f795d4a4a0448f80ab79a27a505257518db562d5c287cc3969bb46d2b9feac938f331a86
Host: idmppwks087:5000
Origin: http://idmppwks087:5000
Referer: http://idmppwks087:5000/dataset/edit/test123
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
_ckan_phase=dataset_new_1&pkg_name=f4342000-7bcb-47f2-886a-0f7af286a674&title=test123&name=test123&notes=test+123&maintainer_email=aakullian&purpose=data&owner_org=255ce615-43f8-48d7-b5c9-aec0fce27f68&private=False&disease=Any&tag_string=&quality=&quality_notes=&ext_startdate=2019-09-24&ext_enddate=2019-09-24&temporal_gaps=&location=Africa%3AAlgeria%3AA%C3%AFn+Defla&spatial=%7B%22type%22%3A+%22Polygon%22%2C+%22coordinates%22%3A+%5B%5B%5B1.528524994850216%2C+35.86028289794933%5D%2C+%5B1.528524994850216%2C+36.45724868774414%5D%2C+%5B2.628351926803646%2C+36.45724868774414%5D%2C+%5B2.628351926803646%2C+35.86028289794933%5D%2C+%5B1.528524994850216%2C+35.86028289794933%5D%5D%5D%7D&spatial_mode=manual&spatial_gaps=&spatial_resolution=&publisher=Tester&url=&acquisition_date=2019-09-24&version=&license_id=notspecified&save=

2. experience following the instruction to enter First Last <alias@server.org> is not good, after typing < user cannot see anything he/she types

**Comment by DLukacevic-IDM** [comment]
converter(key, converted_data, errors, context)
   File "/home/ckan/src/ckan/ckanext/idm/logic/converters.py", line 35, in set_maintainer
     data[(u'maintainer_email',)] = user[u'email']
 KeyError: u'email'

Log from ckan container - looks like the test user didn;t have email key in the users doesn't have an email field defined in extras

After I visited the user profile and clicked on update button the error is no longer happening. 
The fix her should be to check for the case when email doesn't exist and set it on the back end.

The should not happen though for users generated via bootstrap.

**Comment by MeWu-IDM** [comment]
after trying to repro on another deployment with boot-stage steps http://ipadvapp002.ipa.idm.ctr:5000/dataset/test-repro
I think it seems only happening when the maintainer is set different than the logged-in user
if I logged in as mewu, setting it to mewu works, but setting it to someone else with auto-complete fails

**Comment by DLukacevic-IDM** [comment]
This issue is happening for non-sysadmIn users because user_show function is not including email (only email hash). See commit e521a3ee2c7ea05f2f837b87a7f70e308e507cc6 comment for info about the fix.

**Comment by MeWu-IDM** [comment]
verified fixed

**Comment by MeWu-IDM** [comment]
for example when I am in some state, I can't seem to type
![image](https://user-images.githubusercontent.com/40474438/66169257-af756c80-e5f4-11e9-9c7c-d42e9e731816.png)
also, type <mewu@idmod.org> without name will pass the validation but result in empty maintainer field

**Comment by DLukacevic-IDM** [comment]
I see. This should be split into two issues. I would push the remaining problem for phase 2 since all of our researchers are already users and are less likely to use 'contact' option.

**Comment by MeWu-IDM** [comment]
moving remaining issue to #71 and close this
