### ISSUE TITLE
bootstrapping tags

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/ckan#57]
based on the wiki 
we need to have Predefined set will include (example):

RI - contains shapefiles, monthly reports, vaccination coverage records...
MCV2 - Introduction Schedule - Measles-containing-vaccine-second-dose
NightimeLights
that covers a subset of categories in Data Catalog Requirements
https://wiki.idmod.org/pages/viewpage.action?pageId=93228690#DataCatalogRequirements/Features-Requirements

**Comment by DLukacevic-IDM** [comment]
Commit 61bfe8498c71def586def5b0a71225ca12038616 addresses this issue for the most part.

Initially I wanted to create these "free" tags as part of the metadata bootstrap. However, CKAN API doesn't support creation of "free" tags directly. They suggest these should be created as datasets are tagged. So, by parsing tags during datasets import most of these tags are created.

Btw, during metadata bootstrap I create a new vocabulary called "free" which contains these tags. This vocabulary is used by tag parsing during dataset import.

I updated the list of tags in the spec to match what is in metadata.yml

**Comment by MeWu-IDM** [comment]
verified tags created from import is used in auto-complete

**Comment by MeWu-IDM** [comment]
validated the tags are deployed
