### ISSUE TITLE
topics should be consistent with wiki

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/ckan#58]
The topics in bootstrapping should be consistent with the wiki https://wiki.idmod.org/pages/viewpage.action?spaceKey=SP&title=Phase+1%3A+Data+Catalog+Prototype

**Comment by DLukacevic-IDM** [comment]
Update bootstrap metadata.yml, feature files, plugin test, and the spec to make them consistent in respect to topic names. 

Per your suggestion, to make topic names more readable, I set (in metadata.yml) abbreviations to be the title and the full topic name as start of a description.

**Comment by MeWu-IDM** [comment]
verified
