### ISSUE TITLE
deploy stage boot failed

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/ckan#62]
CKAN_PORT is not defined (?)
 getting error on branch 0-idm-proto
Step 15/16 : EXPOSE $CKAN_PORT
ERROR: Service 'ckan' failed to build: EXPOSE requires at least one argument
Error response from daemon: No such container: ckan
Attaching to
Error response from daemon: No such container: ckan
[root@ipadvapp002 deploy]#

**Comment by MeWu-IDM** [comment]
after investigation, I think args CKAN_PORT needs to be passed in to DOCKERFILE
after I did that I can proceed but will hit permission issue
chmod +x maybe needed
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:235: starting container process caused "exec: \"/home/ckan/src/ckan/ckanext/idm/deploy/data/bootstrap.sh\": permission denied"

**Comment by DLukacevic-IDM** [comment]
I didn't see any issues. I followed idm/deploy/ops/README.md and was able to setup and use IDM CKAN istance.

**Comment by MeWu-IDM** [comment]
this was likely docker version issue, close as no repro
