### ISSUE TITLE
Obtain Data Catalog DNS from Ops

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#66]

**Comment by DLukacevic-IDM** [comment]
https://helpdesk.idmod.org/browse/REQUEST-10757?filter=-2

**Comment by DLukacevic-IDM** [comment]
DNS aliases work now:
http://data-catalog:5000
http://data-catalog2:5000

Observed and filed an issues with spatial extension #89   and also filed one task to avoid having to specify port #90 .

**Comment by MeWu-IDM** [comment]
work is complete
