### ISSUE TITLE
Obtain Data Catalog backup share 

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#67]

**Comment by MeWu-IDM** [comment]
need to ask ITOPS if they will have standardized share name

**Comment by DLukacevic-IDM** [comment]
https://helpdesk.idmod.org/browse/REQUEST-10756

**Comment by DLukacevic-IDM** [comment]
We agreed I will try to mont Azure share.

If that doesn't work for us we will just keep on using the current rivendell share (on idmppfil02) untl that storage is retired, when we expect the alternative share will be available.

**Comment by MeWu-IDM** [comment]
no ops
