### ISSUE TITLE
bootstrap should ignore items not defined  in the ymal file

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/ckan#69]
Currently it throws error
File "bootstrap.py", line 52, in main
    create_tag_vocabularies(act, tags)
  File "bootstrap.py", line 172, in create_tag_vocabularies
    for vocabulary_id, tag_list in tags.items():
AttributeError: 'list' object has no attribute 'items'

should be handled

**Comment by DLukacevic-IDM** [comment]
The issue was that [] instead of {} was used in case tags or datasets/resources nodes are missing.

**Comment by MeWu-IDM** [comment]
verified
