### ISSUE TITLE
Acquisition date validation doesn't allow current date

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#73]
Try entering today. It asks for date less or equal yesterday.

**Comment by DLukacevic-IDM** [comment]
The issues was that dates limits were set to module variables. For max acquisition date that didn't work because its value is set the first time the module was called. So, if the system was deployed on 10/8 that is used as a max acq. date.

The fix is ensuring max acq. date is set dynamically for each call.

**Comment by MeWu-IDM** [comment]
tested
