### ISSUE TITLE
Import set Niger as location for some Nigeria datasets

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#76]
[4:30 PM] Christopher Lorton
    Thanks. People always break things: title says "Nigeria" but map shows "Niger" - http://ipadvapp001.ipa.idm.ctr:5000/dataset/nigeria-measles-cases
​[4:31 PM] Christopher Lorton
    Same here: http://ipadvapp001.ipa.idm.ctr:5000/dataset/nigeria-dhis2

**Comment by MeWu-IDM** [comment]
fixed
