### ISSUE TITLE
Improve import data quality: desc., non-unicode, users 

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#77]
Import quality issues:

A number of entries say "Permissions: , later" - not sure what that is about.
--> condition labels like in resources 

URL is not a URL and I am listed as the maintainer! http://ipadvapp001.ipa.idm.ctr:5000/dataset/afghanistan-pakistan-genetic-links
--> add comment that url was not detected
    
Also look at non-unicode values in Caitline's .csv reported in issues #70

**Comment by MeWu-IDM** [comment]
fixed
