### ISSUE TITLE
csv file preview issue

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/ckan#82]
repro:
create a new resource and upload a csv file
set the format to "CSV"
go to the preview page it shows error
![image](https://user-images.githubusercontent.com/40474438/66611506-a72cac80-eb73-11e9-827a-ee5c3028a5b6.png)
it is making calls to external sites and got 503

http://jsonpdataproxy.appspot.com/?callback=jQuery17108975909953261572_1570746797002&url=http%3A%2F%2Fipadvapp002.ipa.idm.ctr%3A5000%2Fdataset%2F0a21af32-484b-4c51-aa6c-517c63bc4d91%2Fresource%2F93fc68fa-0841-455f-abb6-a6ca68fc7f6f%2Fdownload%2Fsite_details111.csv&max-results=490&type=CSV&_=1570746797464

![image](https://user-images.githubusercontent.com/40474438/66611724-49e52b00-eb74-11e9-9a50-d24defca560d.png)

**Comment by DLukacevic-IDM** [comment]
Removed recline_view extension.
