### ISSUE TITLE
Data bootstraping: create users for managers 

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#87]
Managers are not direct members of research groups should have access ability to see all data.

Edward Wenger <ewenger@idmod.org>; 
Guillaume Chabot-Couture <gcouture@intven.com>; 
Charles Eliot <celiot@idmod.org>; 
Rob Baker <rbaker@idmod.org>; 
Robert Hart <rhart@idmod.org>

**Comment by MeWu-IDM** [comment]
rhart is not in the file
also, need to make Edward and Guillaume admin

**Comment by MeWu-IDM** [comment]
verified admins can modify dataset within the research group
