### ISSUE TITLE
Spatial search shows an error on Stage, during long haul test.

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#88]
http://ipadvapp002.ipa.idm.ctr:5000

There was an error while searching. Please try again.

![image](https://user-images.githubusercontent.com/19847181/66787103-4f55b480-ee97-11e9-93bf-522acc8e6791.png)

**Comment by DLukacevic-IDM** [comment]
Looks like Solr is showing an error when trying to run a query with 3445 dataset "id"s:

The logs show Solr error 

Cannot parse \'nigeria AND (id:deb663d5-3ed1-4690-a6c4-ab89ec4b9c57 OR id:59e02545-5fca-456d-9b58-6cea3d82141b OR id:c5ee3542-6a53-45d0-ba81-cc56266d63ad OR... : too many boolean clauses]",)',)

**Comment by DLukacevic-IDM** [comment]
This is most likely caused by the Solr configuration maxBooleanClauses which is at this point set o 1024.

https://github.com/InstituteforDiseaseModeling/ckan/blob/0-idm-proto/ckanext/idm/deploy/solr/solrconfig.xml#L49

This was documented in the CKAN spatial extension, see "Solr configuration issues on legacy PostGIS backend" on page 16 (displayed in pdf, or 20 showed by pdf viewer). 
https://buildmedia.readthedocs.org/media/pdf/ckanext-spatial/latest/ckanext-spatial.pdf

The above pdf suggest setting maxBooleanClauses to 16384.
<maxBooleanClauses>16384</maxBooleanClauses>

**Comment by DLukacevic-IDM** [comment]
Increasing maxBooleanClauses does resolved this error message. 

It remains to be tested whether higher number of datasets impacts system reliability.

**Comment by MeWu-IDM** [comment]
verified search in staging works
