### ISSUE TITLE
Enable using DNS logical name without a port

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#90]
Currently port must be included in the URL 
http://data-catalog:5000/ or
http://data-catalog2:5000/

Either update docker compose to use port 80 or configure port forwarding to VMs.

**Comment by DLukacevic-IDM** [comment]
URLs are now:
http://data-catalog
http://data-catalog2

**Comment by MeWu-IDM** [comment]
verified
