### ISSUE TITLE
Data import: Import Kevin's spreadsheet

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#92]
This requires import script changes because this spreadsheet contains rows grouped by publisher as multiple tables.

**Comment by DLukacevic-IDM** [comment]
Instead of using the spreadsheet (which didn;t contain that much info) I'm scanning dropbox dir for README files and parse them.

**Comment by MeWu-IDM** [comment]
encoding issues found, readme were encoded in ANSI but were loaded as UTF-8 and seeing weird chars for double quote see http://data-catalog/dataset/nigeria-dhs as an example

**Comment by MeWu-IDM** [comment]
I checked with this it seems there are ASCII/Windows 1252 and /ISO-8859-1 encoding
http://idmppwks087:5000/dataset/germany-incidencedata-hagelloch
may need to handle this carefully
```
count = 0
for subdir, dirs, files in os.walk(file_root):
    for f in files:
        if 'readme' in f.lower():
            file_path = os.path.join(subdir, f)
            count += 1
            print(file_path)
            with open(file_path, 'rb') as f:
                # Join binary lines for specified number of lines
                rawdata = b''.join([f.readline() for _ in range(20)])
                encoding = chardet.detect(rawdata)['encoding']
                print(str(encoding))

print(str(count), ' files checked')
```

**Comment by DLukacevic-IDM** [comment]
Added encoding detection and it worked well. Thanks!

**Comment by MeWu-IDM** [comment]
spot check a few different encoded readme, looks good
