### ISSUE TITLE
Data import: Add datasets for Data Service

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#95]
Add 3rd dataset .csv file containing ERA5 and other datasets Data Services team owns.

**Comment by MeWu-IDM** [comment]
tested ckanapi load datasets -I import/datasets-data-services.json -a 1e37c101-1cee-46d2-bd05-7ccd59bb950f -r http://localhost:5000

verify the dataset were correctly loaded
