### ISSUE TITLE
Data import: If unknown, set Research Group based on the maintainer 

### ISSUE THREAD

**Issue by DLukacevic-IDM** [InstituteforDiseaseModeling/ckan#96]

**Comment by MeWu-IDM** [comment]
I am getting error while testing 
u'maintainer_email': [u'Email ewenger is not a valid format']}

**Comment by DLukacevic-IDM** [comment]
Yes, that was a bug. If research group is empty a default was used skipping the code for finding the research group based on the maintainer.

**Comment by MeWu-IDM** [comment]
Tested with attached data that group is NULL or invalid value. verified that the user's group or default is used

[test.txt](https://github.com/InstituteforDiseaseModeling/ckan/files/3764520/test.txt)

python import.py $apikey import/dataset-fields-map-Caitlin.yaml import/test.txt --force
